id: P9010C003
initial_creation_type: input
source_metadata:
  Title: Satyadvayavataradigrantha catustayam
  Editor: Rabten, Sonam
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2000'
  Satyadvayāvatāranāma:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:40:46.839364'
last_modified_at: '2022-03-08T16:40:46.839372'
